{% set version = '1.2.9' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gpg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gpg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gpg/gpg_{{ version }}.tar.gz
  sha256: 1f1d23d5519881cb1735df0e7c6b5bd01e4e8642c4c3a990eaac014028004e4c

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-askpass
    - r-curl
    - gpgme
    - gnupg
  run:
    - r-base
    - r-askpass
    - r-curl
    - gpgme
    - gnupg

test:
  commands:
    - $R -e "library('gpg')"           # [not win]
    - "\"%R%\" -e \"library('gpg')\""  # [win]

about:
  home: https://github.com/jeroen/gpg
  license: MIT
  summary: Bindings to GnuPG for working with OpenGPG (RFC4880) cryptographic methods. Includes
    utilities for public key encryption, creating and verifying digital signatures,
    and managing your local keyring. Some functionality depends on the version of GnuPG
    that is installed on the system. On Windows this package can be used together with
    'GPG4Win' which provides a GUI for managing keys and entering passphrases.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: gpg
# Type: Package
# Title: GNU Privacy Guard for R
# Version: 1.2.9
# Authors@R: person("Jeroen", "Ooms", email = "jeroen@berkeley.edu", comment = c(ORCID = "0000-0002-4035-0289"), role = c("aut", "cre"))
# Description: Bindings to GnuPG for working with OpenGPG (RFC4880) cryptographic methods. Includes utilities for public key encryption, creating and verifying digital signatures, and managing your local keyring. Some functionality depends on the version of GnuPG that is installed on the system. On Windows this package can be used together with 'GPG4Win' which provides a GUI for managing keys and entering passphrases.
# License: MIT + file LICENSE
# SystemRequirements: GPGME: libgpgme-dev (deb), gpgme-devel (rpm) gpgme (brew). On Linux 'haveged' is recommended for generating entropy when using the GPG key generator.
# RoxygenNote: 7.2.3
# Imports: curl, askpass
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# URL: https://github.com/jeroen/gpg
# BugReports: https://github.com/jeroen/gpg/issues
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2023-05-16 13:39:27 UTC; jeroen
# Author: Jeroen Ooms [aut, cre] (<https://orcid.org/0000-0002-4035-0289>)
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2023-05-18 10:30:10 UTC
